### ISSUE TITLE
The Ugly Logo at the app opening

### ISSUE THREAD

**Issue by Spaceshiprace** [Divested-Mobile/Mull-Fenix#197] opened 2024-02-11 17:53 UTC
Please Can you fix that By editing that logo at the app opening or removing it completely because its ugly ass fuck see :

![Screenshot_2024-02-11-15-09-34-400_us spotco fennec_dos_1](https://github.com/Divested-Mobile/Mull-Fenix/assets/156727749/9713dec8-b997-43ec-b612-ae6c83a06658)

**Comment by SkewedZeppelin** [comment] 2024-02-11 20:06
Duplicate of https://github.com/Divested-Mobile/Mull-Fenix/issues/119

**Closed by SkewedZeppelin** 2024-02-11 20:06 UTC

**Comment by Spaceshiprace** [comment] 2024-02-11 20:37
@SkewedZeppelin
I need to notice that I don't care about the logo it self please read the description of the issue I'm talking about the one in the screenshot that appears whenever you open the app.

**Comment by SkewedZeppelin** [comment] 2024-02-11 20:38
That is derived form the logo though, so it is the same.

**Comment by Spaceshiprace** [comment] 2024-02-11 20:39
> That is derived form the logo though, so it is the same.

Ah Ok, Thanks

**Comment by Spaceshiprace** [comment] 2024-02-11 20:41
@SkewedZeppelin

I want to ask, will the logo be changed anytime soon

**Comment by SkewedZeppelin** [comment] 2024-02-11 20:43
It is low priority.
