### ISSUE TITLE
F-Droid Reports a vulerability will Mull

### ISSUE THREAD

**Issue by Hawkeye131** [Divested-Mobile/Mull-Fenix#258] opened 2024-11-01 14:54 UTC
it dose not seem to list it anywhere but it keeps prompting me to uninstall.

**Comment by SkewedZeppelin** [comment] 2024-11-01 15:13
duplicate of https://github.com/Divested-Mobile/Mull-Fenix/issues/255 and https://github.com/Divested-Mobile/Mull-Fenix/issues/256 and https://github.com/Divested-Mobile/Mull-Fenix/issues/254

**Closed by SkewedZeppelin** 2024-11-01 15:13 UTC
